- alias: Startup Notification
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    - delay: "00:00:05"
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.notify_home_available
#    - service: script.notify_home
#      data:
#        message: "Jarvis has started Home Assistant"
