- platform: template
  sensors:
    media_center_activity:
      value_template: '{{ states.remote.living_room.current_activity }}'
    magnetic_3060:
      value_template: >
        {%- if is_state("binary_sensor.ecolink_doorwindow_sensor_sensor_5_0", "off") -%}
          closed
        {%- else -%}
          open
        {%- endif -%}
    motion_3061:
      value_template: >
        {%- if is_state("binary_sensor.ecolink_pir_motion_sensor_sensor_4_0", "off") -%}
          idle
        {%- else -%}
          movement
        {%- endif -%}
    presence_erik:
      value_template: >
        {%- if is_state("device_tracker.onyx", "home") or is_state("device_tracker.arychj_mobile", "home") -%}
          home
        {%- else -%}
          not_home
        {%- endif -%}
    presence_sierra:
      value_template: >
        {%- if is_state("device_tracker.sierra", "home") or is_state("device_tracker.scullati_mobile", "home") -%}
          home
        {%- else -%}
          not_home
        {%- endif -%}
