- platform: template
  sensors:
    media_center_activity:
      value_template: '{{ states.remote.living_room.current_activity }}'
    magnetic_3060:
      value_template: >
        {%- if is_state("binary_sensor.zwave_magnetic_3060_sensor", "off") -%}
          closed
        {%- else -%}
          open
        {%- endif -%}
    magnetic_3072:
      value_template: >
        {%- if is_state("binary_sensor.zwave_magnetic_3072_sensor", "off") -%}
          closed
        {%- else -%}
          open
        {%- endif -%}
    motion_3074:
      value_template: >
        {%- if is_state("binary_sensor.zwave_motion_3074_sensor", "on") -%}
          movement
        {%- else -%}
          idle
        {%- endif -%}
    motion_3073:
      value_template: >
        {%- if is_state("binary_sensor.zwave_motion_3073_sensor", "on") -%}
          movement
        {%- else -%}
          idle
        {%- endif -%}
    presence_erik:
      value_template: >
        {%- if is_state("device_tracker.onyx", "home") or 
               is_state("device_tracker.arychj_mobile", "home") 
        -%}
          home
        {%- else -%}
          not_home
        {%- endif -%}
    presence_sierra:
      value_template: >
        {%- if is_state("device_tracker.sierra", "home") or 
               is_state("device_tracker.scullati_mobile", "home") 
        -%}
          home
        {%- else -%}
          not_home
        {%- endif -%}
    presence_anyone:
      value_template: >
        {%- if is_state("sensor.presence_erik", "home") or 
               is_state("sensor.presence_sierra", "home") 
        -%}
          home
        {%- else -%}
          not_home
        {%- endif -%}
    secret_bing_maps_api_key:
      value_template: !secret bing_maps_api_key
    secret_gps_local_latitude:
      value_template: !secret gps_local_latitude
    secret_gps_local_longitude:
      value_template: !secret gps_local_longitude
    traffic_update_timer:
      value_template: >
        {%- if now().strftime("%a") in ["Mon", "Tue", "Wed", "Thu", "Fri"] and 
               now().strftime("%T") > "07:00" and
               now().strftime("%T") < "09:00"
        -%} 
          {{ (now().timestamp() / 300) | round(0) }}
        {%- else -%} 
          {{ (now().timestamp() / 1800) | round(0) }}
        {%- endif -%} 
