- platform: template
  sensors:
    media_center_activity:
      value_template: '{{ states.remote.living_room.current_activity }}'
    magnetic_3060:
      value_template: >
        {%- if is_state("binary_sensor.ecolink_doorwindow_sensor_sensor_5_0", "off") -%}
          closed
        {%- else -%}
          open
        {%- endif -%}
    magnetic_3072:
      value_template: >
        {%- if is_state("binary_sensor.ecolink_unknown_type0004_id0002_sensor_6_0", "off") -%}
          closed
        {%- else -%}
          open
        {%- endif -%}
    motion_3074:
      value_template: >
        {%- if is_state("binary_sensor.ecolink_pir_motion_sensor_sensor_4_0", "on") -%}
          movement
        {%- else -%}
          idle
        {%- endif -%}
    motion_3073:
      value_template: >
        {%- if is_state("binary_sensor.ecolink_motion_detector_sensor_9_0", "on") -%}
          movement
        {%- else -%}
          idle
        {%- endif -%}
    presence_erik:
      value_template: >
        {%- if is_state("device_tracker.onyx", "home") or is_state("device_tracker.arychj_mobile", "home") -%}
          home
        {%- else -%}
          not_home
        {%- endif -%}
    presence_sierra:
      value_template: >
        {%- if is_state("device_tracker.sierra", "home") or is_state("device_tracker.scullati_mobile", "home") -%}
          home
        {%- else -%}
          not_home
        {%- endif -%}
