- alias: Announcement Complete
  trigger:
    - platform: state
      entity_id: media_player.mc_speakers
      from: 'playing'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ states.media_player.mc_speakers.attributes.media_title != "notification.mp3" }}'
      - condition: state
        entity_id: input_boolean.announcement_in_progress
        state: 'on'
  action:
    - delay: '00:00:01'
    - service: media_player.sonos_restore
      entity_id: media_player.mc_speakers
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.announcement_in_progress

