- alias: Sierra is arriving
  trigger:
    platform: state
    entity_id: sensor.presence_erik
    from: not_home
    to: home
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.arriving_sierra
    - delay: "00:10:00"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.arriving_sierra
