- alias: Trash day reminder
  trigger:
    platform: time
    at: "21:30:00"
  condition:
  - condition: time
    weekday: [wed, sun]
  action:
    service: script.announce
    data:
      message: "Tomorrow is trash day. Have you taken out the trash yet?"
