- alias: Test Trigger
  trigger:
    - platform: state
      entity_id: input_boolean.test_trigger
      from: 'off'
      to: 'on'
  action:
    service: script.entryway_arrival
    data:
      variables:
        entity_id: group.entryway
        minutes: 1
